# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='friends',
        ),
        migrations.AddField(
            model_name='member',
            name='friend',
            field=models.ManyToManyField(blank=True, null=True, related_name='_member_friend_+', to='chat.Member'),
        ),
    ]
