# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20160203_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='/upload_img/'),
        ),
    ]
