# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20160215_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='intro',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
