# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_member_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='logo',
            field=models.ImageField(blank=True, default='upload_img/logo1.jpg', null=True, upload_to='upload_img'),
        ),
    ]
